[package]
name = "uptime_probe"
version = "0.1.0"
authors = ["Federico Gimenez <federico@web3.foundation>"]
edition = "2018"

[dependencies]
prometheus = "0.4"
serde = "1.0"
serde_derive = "1.0.90"
serde_yaml = "0.8"
tempfile = "3"
