version: 2

jobs:
  cargoTests:
    docker:
      - image: rustlang/rust:nightly-slim
    steps:
      - checkout
      - run:
          command: |
            apt update && apt install -y libssl-dev pkg-config
            cargo test

  buildImage:
    docker:
      - image: web3f/ci-commons:v1.8.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/build-image.sh web3f/uptime-probe .

  integrationTests:
    docker:
      - image: web3f/ci-commons:v1.8.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          description: run integration tests
          command: |
            /scripts/integration-tests.sh

  publishImage:
    docker:
      - image: web3f/ci-commons:v1.8.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            /scripts/publish-image.sh web3f/uptime-probe

  publishChart:
    docker:
      - image: web3f/ci-commons:v1.8.0
    steps:
      - checkout
      - run:
          command: |
            /scripts/publish-chart.sh

  deploy:
    docker:
      - image: web3f/ci-commons:v1.8.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            ./scripts/deploy.sh

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - cargoTests:
          filters:
            tags:
              only: /.*/
      - buildImage:
          filters:
            tags:
              only: /.*/
      - integrationTests:
          filters:
            tags:
              only: /.*/
      - publishImage:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - cargoTests
            - buildImage
            - integrationTests
      - publishChart:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - cargoTests
            - buildImage
            - integrationTests
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - publishChart
            - publishImage
