apiVersion: v1
kind: ConfigMap
metadata:
  name: uptime-probe
data:
  configuration.yaml: |
    period: 300
    port: {{ .Values.port }}
    sites:
    - url: "https://polkadot.network/"
      needles: ["multi-chain", "interoperability", "scalability"]
    - url: "https://web3.foundation/"
      needles: ["decentralized", "protocols", "projects"]
