apiVersion: v1
kind: ConfigMap
metadata:
  name: uptime-probe
data:
  configuration.yaml: |
    period: 300
    port: {{ .Values.port }}
    sites:
    - url: "https://polkadot.network"
      needles: []
    - url: "https://web3.foundation/"
      needles: []
    - url: "https://research.web3.foundation/en/latest/"
      needles: []
    - url: "https://wiki.web3.foundation/en/latest/"
      needles: []
    - url: "https://wiki.polkadot.network/en/latest/"
      needles: []
    - url: "https://riot.w3f.tech/"
      needles: []
    - url: "https://web3.foundation/.well-known/matrix/server"
      needles: []
    - url: "https://kusama.network"
      needles: []
