apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-probe
  labels:
    app: uptime-probe
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: uptime-probe
  template:
    metadata:
      labels:
        app: uptime-probe
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: uptime-probe
        image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        args:
        - /app/uptime-probe
        - /etc/uptime-probe/configuration.yaml
        ports:
        - name: http
          containerPort: {{ .Values.port }}
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: {{ .Values.port }}
          initialDelaySeconds: 30
          timeoutSeconds: 30
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
          limits:
            cpu: 200m
            memory: 400Mi
        volumeMounts:
        - name: config
          mountPath: /etc/uptime-probe
      volumes:
      - name: config
        configMap:
          name: uptime-probe
