environment: production
origin:
port: 8080

image:
  repo: web3f/uptime-probe
  tag: latest

sites:
- url: "https://polkadot.network"
  needles: []
- url: "https://web3.foundation/"
  needles: []
- url: "https://research.web3.foundation/en/latest/"
  needles: []
- url: "https://wiki.web3.foundation/en/latest/"
  needles: []
- url: "https://wiki.polkadot.network/docs/en/"
  needles: []
- url: "https://riot.w3f.tech/"
  needles: []
- url: "https://web3.foundation/.well-known/matrix/server"
  needles: []
- url: "https://kusama.network"
  needles: []
- url: "https://claims.polkadot.network"
  needles: []
- url: "https://wiki.polkadot.network/docs/en/kusama-index"
  needles: []
- url: "https://wiki.polkadot.network/docs/en/kusama-claims"
  needles: []
- url: "https://wiki.polkadot.network/docs/en/kusama-timeline"
  needles: []
- url: "https://wiki.polkadot.network/docs/en/kusama-faucet"
  needles: []
- url: "https://wiki.polkadot.network/docs/en/learn-identity"
  needles: []
- url: "https://wiki.polkadot.network/docs/en/learn-governance"
  needles: []
- url: "https://wiki.polkadot.network/docs/en/maintain-guides-how-to-validate-kusama"
  needles: []
- url: "https://wiki.polkadot.network/docs/en/build-build-with-polkadot"
  needles: []
- url: "https://wiki.polkadot.network/docs/en/kusama-bug-bounty"
  needles: []
- url: "https://wiki.polkadot.network/docs/en/kusama-adverserial-cheatsheet"
  needles: []
- url: "https://wiki.polkadot.network/docs/en/kusama-community"
  needles: []
- url: "https://wiki.polkadot.network/docs/en/kusama-coc"
  needles: []
- url: "https://remarkable.w3f.tech"
  needles: []
- url: "https://statement.polkadot.network/saft.html"
  needles: []
- url: "https://statement.polkadot.network/regular.html"
  needles: []
- url: "https://polkadot-api.w3f.community/vesting/Di9whaYj3nvDZr3hjsDGwgrEowz16HvSfKaiHRprRGvZa8x"
  needles: []
- url: "https://kusama-api.w3f.community/balance/DTLcUu92NoQw4gg6VmNgXeYQiNywDhfYMQBPYg2Y1W6AkJF"
  needles: []
